### ISSUE TITLE
error when trying to require local file

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/lazy-cache#6]
for example

``` js
var fn = require
require = utils

require('quxify')
require('./foobarify')

require = fn
module.exports = utils
```

throws following

```
TypeError: Cannot read property 'length' of null
       at camelcase (/home/charlike/latest/lazy-arrayify/node_modules/lazy-cache/index.js:105:10)
       at proxy (/home/charlike/latest/lazy-arrayify/node_modules/lazy-cache/index.js:27:13)
```

**Comment by doowb** [comment]
Do you have a complete example? I'm trying to reproduce the error, but I'm not able to.

**Comment by tunnckoCore** [comment]
Yea I have. May be it was needed to mention that I'm trying to require local file and give it an alias

``` js
var fn = require
require = utils

require('isarray', 'isArray')
require('./arrayify')

// both not work
// require('./arrayify', 'arrayify')

require = fn
module.exports = utils
```

**Comment by tunnckoCore** [comment]
Okey that's strange, it works. Lol, sorry.
